# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true
  cyclop:
    max-complexity: 14
  funlen:
    lines: 65

linters:
  enable-all: true
  disable:
    - lll
    - maligned
    - gochecknoglobals
    - gomnd
    - wrapcheck
    - paralleltest
    - forbidigo
    - exhaustivestruct
    - interfacer # deprecated
    - forcetypeassert
    - scopelint # deprecated
    - ifshort # too many false positives
    - golint # deprecated
    - varnamelen
    - tagliatelle
    - errname
    - ireturn
    - exhaustruct
    - nonamedreturns
    - nosnakecase
    - structcheck
    - varcheck
    - deadcode
    - testableexamples
    - dupword

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - gosec
        - gomnd
        - goconst
        - goerr113
        - noctx
        - funlen
        - dupl
        - structcheck
        - unused
        - unparam
        - nosnakecase
      path: "_test.go"
    - linters:
        - errcheck # Error checking omitted for brevity.
        - gosec
      path: "example_"

